### ISSUE TITLE
ACS Encoding Error

### ISSUE THREAD

**Issue by trevorspreadbury** [MaterialEyes/exsclaim#12]
ACS scraping leads to errors:

```
Traceback (most recent call last):
  File "run.py", line 48, in <module>
    pipeline.run(journal_scraper=j, caption_distributor=c, figure_separator=f)
  File "/home/trevor/Documents/argonne/exsclaim/exsclaim/pipeline.py", line 137, in run
    self.exsclaim_dict = tool.run(self.query_dict,self.exsclaim_dict)
  File "/home/trevor/Documents/argonne/exsclaim/exsclaim/tool.py", line 166, in run
    articles = self._get_articles(j_instance)
  File "/home/trevor/Documents/argonne/exsclaim/exsclaim/tool.py", line 142, in _get_articles
    articles = j_instance.get_article_extensions(self.articles_visited)
  File "/home/trevor/Documents/argonne/exsclaim/exsclaim/journal.py", line 185, in get_article_extensions
    start_page, stop_page, total_articles = self.get_page_info(soup)
  File "/home/trevor/Documents/argonne/exsclaim/exsclaim/journal.py", line 373, in get_page_info
    totalResults = int(soup.find('span', {'class': "result__count"}).text)
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by trevorspreadbury** [comment]
resolved by updates to ACS class
